### ISSUE TITLE
translation permission request question(edge-compute-knitted-dog-hats)

### ISSUE THREAD

**Issue by jung-han** [AustinGil/AustinGil#1]
Hi @AustinGil! I'm jung, a front-end developer At Korean FE Article Team.

First of all, I am sorry that I chose this issue while looking for a place to contact.

I read an article([edge-compute-knitted-dog-hats](https://austingil.com/edge-compute-knitted-dog-hats/)). It was a very good article and it was very helpful. I am going to translate the article into Korean and post it on Korean FE Article mailing substack(https://kofearticle.substack.com/), is it okay?

Korean FE Article is an activity that picks good FE articles every week, translates them into Korean, and shares them.
It is not used commercially, and the source must be identified.

Please think about it and reply. I'll wait!

**Comment by AustinGil** [comment]
Hello,

Thank you so much for reaching out. I appreciate you asking permission before doing so, and yes, it's fine. I think it's great that you want to share my work. I just ask that you include a link back to the original source.

Could you please send me the link when it's published so I can also link to it from the original?

**Comment by jung-han** [comment]
Here is the address where the translation was posted (https://bit.ly/3N9gkKf) and it was sent through this mailing(https://kofearticle.substack.com/p/korean-fe-article-edge-) 

It's not many, but around 1900 people are expected to receive the mail. Thanks for writing a nice article! We will close this issue. Have a good day! 🌝
